from World import World
import time
from _datetime import date, timedelta
import sys


# log to file
file = open('cwb-war.txt', 'a')
sys.stdout = file

# placing information of each canadian province and its borders in regionData
regionData = list([])
regionData.append(("ABRANCHES", ["PILARZINHO", "SÃO LOURENÇO", "TABOÃO", "BARREIRINHA", "CACHOEIRA"]))
regionData.append(("ÁGUA VERDE", ["CENTRO", "SEMINÁRIO", "VILA IZABEL", "PAROLIN", "REBOUÇAS", "BATEL", "PORTÃO", "GUAÍRA"]))
regionData.append(("AHÚ", ["SÃO LOURENÇO", "JUVEVÊ", "BOA VISTA", "CABRAL", "CENTRO CÍVICO", "BOM RETIRO"]))
regionData.append(("ALTO BOQUEIRÃO", ["BOQUEIRÃO", "SÍTIO CERCADO", "GANCHINHO", "XAXIM"]))
regionData.append(("ALTO DA GLÓRIA", ["JUVEVÊ", "ALTO DA RUA XV", "CENTRO", "CENTRO CÍVICO"]))
regionData.append(("ALTO DA RUA XV", ["JUVEVÊ", "HUGO LANGE", "ALTO DA GLÓRIA", "JARDIM SOCIAL", "TARUMÃ", "CENTRO", "CRISTO REI", "JARDIM BOTÂNICO"]))
regionData.append(("ATUBA", ["TINGUI", "BAIRRO ALTO", "SANTA CÂNDIDA"]))
regionData.append(("AUGUSTA", ["CIDADE INDUSTRIAL DE CURITIBA", "RIVIERA", "SÃO MIGUEL"]))
regionData.append(("BACACHERI", ["BOA VISTA", "CABRAL", "HUGO LANGE", "JARDIM SOCIAL", "TINGUI", "BAIRRO ALTO", "SANTA CÂNDIDA"]))
regionData.append(("BAIRRO ALTO", ["JARDIM SOCIAL", "TARUMÃ", "TINGUI", "ATUBA", "BACACHERI", "CAPÃO DA IMBUIA"]))
regionData.append(("BARREIRINHA", ["SÃO LOURENÇO", "ABRANCHES", "BOA VISTA", "CACHOEIRA", "SANTA CÂNDIDA"]))
regionData.append(("BATEL", ["CENTRO", "CAMPINA DO SIQUEIRA", "SEMINÁRIO", "BIGORRILHO", "ÁGUA VERDE"]))
regionData.append(("BIGORRILHO", ["CENTRO", "MERCÊS", "CASCATINHA", "CAMPINA DO SIQUEIRA", "BATEL", "MOSSUNGUÊ", "SANTO INÁCIO"]))
regionData.append(("BOA VISTA", ["SÃO LOURENÇO", "BARREIRINHA", "CABRAL", "TINGUI", "BACACHERI", "SANTA CÂNDIDA", "AHÚ"]))
regionData.append(("BOM RETIRO", ["PILARZINHO", "SÃO LOURENÇO", "MERCÊS", "SÃO FRANCISCO", "CENTRO CÍVICO", "VISTA ALEGRE", "AHÚ"]))
regionData.append(("BOQUEIRÃO", ["HAUER", "ALTO BOQUEIRÃO", "UBERABA", "XAXIM"]))
regionData.append(("BUTIATUVINHA", ["SÃO BRAZ", "LAMENHA PEQUENA", "SANTA FELICIDADE", "ORLEANS"]))
regionData.append(("CABRAL", ["JUVEVÊ", "BOA VISTA", "HUGO LANGE", "BACACHERI", "AHÚ"]))
regionData.append(("CACHOEIRA", ["ABRANCHES", "BARREIRINHA", "SANTA CÂNDIDA"]))
regionData.append(("CAJURU", ["JARDIM DAS AMÉRICAS", "CAPÃO DA IMBUIA", "CRISTO REI", "JARDIM BOTÂNICO", "UBERABA"]))
regionData.append(("CAMPINA DO SIQUEIRA", ["SEMINÁRIO", "BIGORRILHO", "BATEL", "MOSSUNGUÊ", "SANTO INÁCIO"]))
regionData.append(("CAMPO COMPRIDO", ["SANTA QUITÉRIA", "SEMINÁRIO", "FAZENDINHA", "CIDADE INDUSTRIAL DE CURITIBA", "MOSSUNGUÊ", "ORLEANS"]))
regionData.append(("CAMPO DE SANTANA", ["TATUQUARA", "UMBARÁ", "CAXIMBA"]))
regionData.append(("CAPÃO DA IMBUIA", ["TARUMÃ", "BAIRRO ALTO", "CRISTO REI", "JARDIM BOTÂNICO", "CAJURU"]))
regionData.append(("CAPÃO RASO", ["NOVO MUNDO", "CIDADE INDUSTRIAL DE CURITIBA", "PINHEIRINHO", "XAXIM"]))
regionData.append(("CASCATINHA", ["SÃO JOÃO", "SANTA FELICIDADE", "MERCÊS", "VISTA ALEGRE", "BIGORRILHO", "SANTO INÁCIO"]))
regionData.append(("CAXIMBA", ["CAMPO DE SANTANA"]))
regionData.append(("CENTRO", ["ALTO DA RUA XV", "ALTO DA GLÓRIA", "MERCÊS", "SÃO FRANCISCO", "CENTRO CÍVICO", "BIGORRILHO", "ÁGUA VERDE", "REBOUÇAS", "BATEL", "CRISTO REI", "JARDIM BOTÂNICO"]))
regionData.append(("CENTRO CÍVICO", ["JUVEVÊ", "ALTO DA GLÓRIA", "CENTRO", "SÃO FRANCISCO", "BOM RETIRO", "AHÚ"]))
regionData.append(("CIDADE INDUSTRIAL DE CURITIBA", ["NOVO MUNDO", "FAZENDINHA", "AUGUSTA", "CAMPO COMPRIDO", "RIVIERA", "ORLEANS", "TATUQUARA", "PINHEIRINHO", "CAPÃO RASO", "SÃO MIGUEL"]))
regionData.append(("CRISTO REI", ["ALTO DA RUA XV", "TARUMÃ", "CENTRO", "CAPÃO DA IMBUIA", "JARDIM BOTÂNICO", "CAJURU"]))
regionData.append(("FANNY", ["PAROLIN", "LINDÓIA", "GUAÍRA", "NOVO MUNDO", "HAUER", "XAXIM"]))
regionData.append(("FAZENDINHA", ["SANTA QUITÉRIA", "PORTÃO", "NOVO MUNDO", "CAMPO COMPRIDO", "CIDADE INDUSTRIAL DE CURITIBA"]))
regionData.append(("GANCHINHO", ["ALTO BOQUEIRÃO", "UMBARÁ", "SÍTIO CERCADO"]))
regionData.append(("GUABIROTUBA", ["PRADO VELHO", "JARDIM DAS AMÉRICAS", "JARDIM BOTÂNICO", "HAUER", "UBERABA"]))
regionData.append(("GUAÍRA", ["ÁGUA VERDE", "PAROLIN", "LINDÓIA", "PORTÃO", "FANNY"]))
regionData.append(("HAUER", ["PAROLIN", "PRADO VELHO", "FANNY", "GUABIROTUBA", "BOQUEIRÃO", "UBERABA", "XAXIM"]))
regionData.append(("HUGO LANGE", ["JUVEVÊ", "ALTO DA RUA XV", "CABRAL", "JARDIM SOCIAL", "BACACHERI"]))
regionData.append(("JARDIM BOTÂNICO", ["ALTO DA RUA XV", "CENTRO", "PRADO VELHO", "REBOUÇAS", "GUABIROTUBA", "JARDIM DAS AMÉRICAS", "CAPÃO DA IMBUIA", "CRISTO REI", "CAJURU"]))
regionData.append(("JARDIM DAS AMÉRICAS", ["PRADO VELHO", "GUABIROTUBA", "JARDIM BOTÂNICO", "CAJURU", "UBERABA"]))
regionData.append(("JARDIM SOCIAL", ["ALTO DA RUA XV", "HUGO LANGE", "TARUMÃ", "BAIRRO ALTO", "BACACHERI"]))
regionData.append(("JUVEVÊ", ["ALTO DA RUA XV", "CABRAL", "HUGO LANGE", "ALTO DA GLÓRIA", "CENTRO CÍVICO", "AHÚ"]))
regionData.append(("LAMENHA PEQUENA", ["BUTIATUVINHA", "SANTA FELICIDADE"]))
regionData.append(("LINDÓIA", ["PAROLIN", "PORTÃO", "GUAÍRA", "FANNY", "NOVO MUNDO"]))
regionData.append(("MERCÊS", ["CENTRO", "SÃO FRANCISCO", "BOM RETIRO", "VISTA ALEGRE", "CASCATINHA", "BIGORRILHO", "SANTO INÁCIO"]))
regionData.append(("MOSSUNGUÊ", ["CAMPINA DO SIQUEIRA", "SEMINÁRIO", "BIGORRILHO", "CAMPO COMPRIDO", "SANTO INÁCIO", "ORLEANS"]))
regionData.append(("NOVO MUNDO", ["LINDÓIA", "PORTÃO", "FANNY", "FAZENDINHA", "CIDADE INDUSTRIAL DE CURITIBA", "CAPÃO RASO", "XAXIM"]))
regionData.append(("ORLEANS", ["SÃO BRAZ", "BUTIATUVINHA", "CAMPO COMPRIDO", "CIDADE INDUSTRIAL DE CURITIBA", "MOSSUNGUÊ", "RIVIERA", "SANTO INÁCIO"]))
regionData.append(("PAROLIN", ["ÁGUA VERDE", "PRADO VELHO", "REBOUÇAS", "LINDÓIA", "GUAÍRA", "FANNY", "HAUER"]))
regionData.append(("PILARZINHO", ["SÃO LOURENÇO", "ABRANCHES", "TABOÃO", "SÃO JOÃO", "BOM RETIRO", "VISTA ALEGRE"]))
regionData.append(("PINHEIRINHO", ["CIDADE INDUSTRIAL DE CURITIBA", "TATUQUARA", "SÍTIO CERCADO", "CAPÃO RASO", "XAXIM"]))
regionData.append(("PORTÃO", ["SANTA QUITÉRIA", "VILA IZABEL", "ÁGUA VERDE", "LINDÓIA", "GUAÍRA", "NOVO MUNDO", "FAZENDINHA"]))
regionData.append(("PRADO VELHO", ["PAROLIN", "REBOUÇAS", "GUABIROTUBA", "JARDIM DAS AMÉRICAS", "JARDIM BOTÂNICO", "HAUER"]))
regionData.append(("REBOUÇAS", ["CENTRO", "ÁGUA VERDE", "PAROLIN", "PRADO VELHO", "JARDIM BOTÂNICO"]))
regionData.append(("RIVIERA", ["AUGUSTA", "CIDADE INDUSTRIAL DE CURITIBA", "ORLEANS"]))
regionData.append(("SANTA CÂNDIDA", ["BARREIRINHA", "BOA VISTA", "CACHOEIRA", "TINGUI", "ATUBA", "BACACHERI"]))
regionData.append(("SANTA FELICIDADE", ["SÃO JOÃO", "SÃO BRAZ", "BUTIATUVINHA", "LAMENHA PEQUENA", "CASCATINHA", "SANTO INÁCIO"]))
regionData.append(("SANTA QUITÉRIA", ["SEMINÁRIO", "VILA IZABEL", "PORTÃO", "FAZENDINHA", "CAMPO COMPRIDO"]))
regionData.append(("SANTO INÁCIO", ["SÃO BRAZ", "SANTA FELICIDADE", "MERCÊS", "CASCATINHA", "CAMPINA DO SIQUEIRA", "BIGORRILHO", "MOSSUNGUÊ", "ORLEANS"]))
regionData.append(("SÃO BRAZ", ["BUTIATUVINHA", "SANTA FELICIDADE", "SANTO INÁCIO", "ORLEANS"]))
regionData.append(("SÃO FRANCISCO", ["CENTRO", "MERCÊS", "CENTRO CÍVICO", "BOM RETIRO"]))
regionData.append(("SÃO JOÃO", ["PILARZINHO", "SANTA FELICIDADE", "VISTA ALEGRE", "CASCATINHA"]))
regionData.append(("SÃO LOURENÇO", ["PILARZINHO", "ABRANCHES", "BARREIRINHA", "BOA VISTA", "BOM RETIRO", "AHÚ"]))
regionData.append(("SÃO MIGUEL", ["AUGUSTA", "CIDADE INDUSTRIAL DE CURITIBA"]))
regionData.append(("SEMINÁRIO", ["SANTA QUITÉRIA", "CAMPINA DO SIQUEIRA", "VILA IZABEL", "ÁGUA VERDE", "BATEL", "CAMPO COMPRIDO", "MOSSUNGUÊ"]))
regionData.append(("SÍTIO CERCADO", ["ALTO BOQUEIRÃO", "TATUQUARA", "UMBARÁ", "PINHEIRINHO", "GANCHINHO", "XAXIM"]))
regionData.append(("TABOÃO", ["PILARZINHO", "ABRANCHES"]))
regionData.append(("TARUMÃ", ["ALTO DA RUA XV", "JARDIM SOCIAL", "BAIRRO ALTO", "CAPÃO DA IMBUIA", "CRISTO REI"]))
regionData.append(("TATUQUARA", ["CIDADE INDUSTRIAL DE CURITIBA", "UMBARÁ", "PINHEIRINHO", "SÍTIO CERCADO", "CAMPO DE SANTANA"]))
regionData.append(("TINGUI", ["BOA VISTA", "BAIRRO ALTO", "ATUBA", "BACACHERI", "SANTA CÂNDIDA"]))
regionData.append(("UBERABA", ["GUABIROTUBA", "JARDIM DAS AMÉRICAS", "BOQUEIRÃO", "HAUER", "CAJURU"]))
regionData.append(("UMBARÁ", ["TATUQUARA", "SÍTIO CERCADO", "CAMPO DE SANTANA", "GANCHINHO"]))
regionData.append(("VILA IZABEL", ["SANTA QUITÉRIA", "SEMINÁRIO", "ÁGUA VERDE", "PORTÃO"]))
regionData.append(("VISTA ALEGRE", ["PILARZINHO", "SÃO JOÃO", "MERCÊS", "BOM RETIRO", "CASCATINHA"]))
regionData.append(("XAXIM", ["FANNY", "NOVO MUNDO", "BOQUEIRÃO", "HAUER", "ALTO BOQUEIRÃO", "PINHEIRINHO", "SÍTIO CERCADO", "CAPÃO RASO"]))
canada = World(regionData)
current_date = date(2020, 1, 1)

print("---------------------------------------------------")
print(str(current_date.month)+'\\'+str(current_date.day)+'\\'+str(current_date.year))
print(canada)
print("---------------------------------------------------")


while canada.not_united():
    #time.sleep(.01)
    current_date = current_date + timedelta(1)
    canada.update()
    #print("---------------------------------------------------")
    print(str(current_date.month) + '\\' + str(current_date.day) + '\\' + str(current_date.year))
    print(canada)
    print("---------------------------------------------------")
print("Vencedor é: ", canada.winner().name())
print("-- CWB WAR SIMULATOR FINISH  --")
file.close()